Ext.define('BuskartApp.model.AyohaStorePayment.AyohaStorePaymentModel', {
    extend: 'Ext.data.Model',
    config: {
        fields: [
        'PaymentNo',
        'PaymentNoDisplay',
         'CreatedDate',
         'OrderNo',
         'GrandTotal',
        'PaymentAmount',
      'PaymentMethod',
      'PaymentStatus',
     'DeliveryName',
      'DeliveryCharge',
      'MembershipDiscount',
'VoucherDiscount',
'DeliveryAddress_StreetName',
'DeliveryAddress_Town',
'DeliveryAddress_Postcode',
'DeliveryAddress_StateCode',
'DeliveryAddress_CountryCode',
'ReferenceName',
'ReferencePhoneNo',
'NoteToSeller',
'MerchantPointEarn',
'AyohaPointEarn',
'MembershipCardCode',
'OrderNo',
'DisplayOrderNo',
'TotalQuantity',
'SubTotal',
'ItemSumPrice',
'ItemName',
'ItemQuantity',
'ItemPrice',
'ItemPriceDiscount',
'ItemPriceDiscountRate',
'EnterpriseName',
'EnterpriseLogoPath',
'EnterpriseAddress',
'EnterpriseRegistrationNo',
'EnterpriseTagLine',
'EnterprisePhoneNo',
'EnterpriseEmail',
'EnterpriseWebsite',
'PayerName',
'MembershipCardName',
'MembershipCardBackgroundImg',
'Row_num',

        ]
    }
});
